name: Run Postman Collection

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman + HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Tests
        run: |
          newman run ./test1.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./postman-report.html
        continue-on-error: true

      # Optional: commit the HTML report back into the repo
      - name: Commit HTML Report
        run: |
          git config --global user.name "manish3778"
          git config --global user.email "manishkumar17@karunya.edu.in"
          git add postman-report.html
          git commit -m "Add Postman HTML test report"
          git push
          
          git add postman-report.html
          git commit -m "Add Postman HTML test report"
          git push
